# The `torch.nn` Module in PyTorch

The `torch.nn` module in PyTorch is a core library that provides a wide array of classes and functions designed to help developers build neural networks efficiently and effectively. It abstracts the complexity of creating and training neural networks by offering pre-built layers, loss functions, activation functions, and other utilities, enabling you to focus on designing and experimenting with model architectures.

## Key Components of `torch.nn`

### 1. Modules (Layers)

- **`nn.Module`**  
  The base class for all neural network modules. Your custom models and layers should subclass this class.

- **Common Layers**
  - `nn.Linear` → Fully connected layer
  - `nn.Conv2d` → Convolutional layer
  - `nn.LSTM` → Recurrent layer
  - And many more
  

### 2. Activation Functions

Activation functions introduce non-linearity into neural networks, allowing models to learn complex patterns.

Common activation functions include:

- `nn.ReLU`
- `nn.Sigmoid`
- `nn.Tanh`


### 3. Loss Functions

Loss functions measure the difference between the model’s predictions and the actual targets.

Some commonly used loss functions are:

- `nn.CrossEntropyLoss`
- `nn.MSELoss`
- `nn.NLLLoss`


### 4. Container Modules

- **`nn.Sequential`**  
  A sequential container used to stack layers in order, making model building simpler and cleaner.


### 5. Regularization and Dropout

These layers help reduce overfitting and improve model generalization.

Examples include:

- `nn.Dropout`
- `nn.BatchNorm2d`

# Example Simple Code

In [1]:
# Import PyTorch library
import torch

# Import neural network module from PyTorch
import torch.nn as nn


# Create a custom neural network model class
# Every PyTorch model must inherit from nn.Module
class Model(nn.Module):

    # Constructor method
    # num_features -> number of input features in the dataset
    def __init__(self, num_features):

        # Call the constructor of the parent class (nn.Module)
        # This is required to properly initialize the neural network
        super().__init__()

        # Define a fully connected (linear) layer
        # Input size  -> num_features
        # Output size -> 1 (for binary classification)
        self.linear = nn.Linear(num_features, 1)

        # Define sigmoid activation function
        # Converts output into probability values between 0 and 1
        self.sigmoid = nn.Sigmoid()

    # Forward propagation method
    # Defines how data flows through the network
    def forward(self, features):

        # Pass input features through linear layer
        out = self.linear(features)

        # Apply sigmoid activation on linear output
        out = self.sigmoid(out)

        # Return final prediction
        return out

In [2]:
# create dataset
features = torch.rand(10,5,requires_grad=True)

# create model
model = Model(features.shape[1])

# call model
model(features)

tensor([[0.5538],
        [0.5650],
        [0.5223],
        [0.4306],
        [0.5428],
        [0.5471],
        [0.5297],
        [0.5682],
        [0.5658],
        [0.5236]], grad_fn=<SigmoidBackward0>)

In [4]:
# weights
model.linear.weight

Parameter containing:
tensor([[ 0.3324, -0.2354, -0.0145, -0.4312,  0.0787]], requires_grad=True)

In [5]:
# to visualization of model
!pip install torchinfo

In [6]:
from torchinfo import summary

summary(model,input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

# code for hidden layer

In [7]:
# create model class
import torch
import torch.nn as nn

class Model(nn.Module):

  def __init__(self,num_features):
    super().__init__()
    self.network = nn.Sequential(
        nn.Linear(num_features,3),
        nn.ReLU(),
        nn.Linear(3,1),
        nn.Sigmoid()
    )

  def forward(self,features):
    return self.network(features)


In [8]:
# create dataset
features = torch.rand(10,5,requires_grad=True)

# create model
model = Model(features.shape[1])

# call model
model(features)

tensor([[0.5329],
        [0.5409],
        [0.5384],
        [0.5372],
        [0.5380],
        [0.5383],
        [0.5360],
        [0.5396],
        [0.5387],
        [0.5336]], grad_fn=<SigmoidBackward0>)

In [9]:
summary(model,input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Sequential: 1-1                        [10, 1]                   --
│    └─Linear: 2-1                       [10, 3]                   18
│    └─ReLU: 2-2                         [10, 3]                   --
│    └─Linear: 2-3                       [10, 1]                   4
│    └─Sigmoid: 2-4                      [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

# torch.optim in PyTorch

`torch.optim` is a module in PyTorch that provides a variety of optimization algorithms used to update the parameters of your model during training.

It includes common optimizers like:

- `SGD` (Stochastic Gradient Descent)
- `Adam`
- `RMSprop`
- And many more

It handles weight updates efficiently, including additional features like:

- Learning rate scheduling
- Weight decay (regularization)


# model.parameters() in PyTorch

The `model.parameters()` method in PyTorch retrieves an iterator over all the trainable parameters (weights and biases) in a model.

These parameters are instances of `torch.nn.Parameter` and include:

## 1. Weights

The weight matrices of layers such as:

- `nn.Linear`
- `nn.Conv2d`
- etc.


## 2. Biases

The bias terms of layers (if they exist).


# Why It Is Important

The optimizer uses these parameters to:

- Compute gradients
- Update weights
- Update biases
- Improve the model during training


# Example

```python id="bn5xwu"
import torch.optim as optim

optimizer = optim.Adam(model.parameters(), lr=0.001)

# Complete PyTorch Neural Network Pipeline


In [10]:
# Import Libraries
import torch
import torch.nn as nn
import torch.optim as optim

In [11]:
# Create Neural Network Using nn.Module
class Model(nn.Module):

    def __init__(self, num_features):

        # Call parent class constructor
        super().__init__()

        # Build neural network using Sequential
        self.network = nn.Sequential(

            # Input Layer → Hidden Layer
            nn.Linear(num_features, 3),

            # Built-in activation function
            nn.ReLU(),

            # Hidden Layer → Output Layer
            nn.Linear(3, 1),

            # Output activation function
            nn.Sigmoid()
        )

    # Forward propagation
    def forward(self, features):

        return self.network(features)

In [12]:
# Create Model Object
# Example:
# num_features = 5

model = Model(num_features=5)

In [14]:
# Define Loss Function
criterion = nn.BCELoss()

In [15]:
# Define Optimizer
optimizer = optim.Adam(
    model.parameters(),
    lr=0.01
)

In [16]:
# Dummy Training Data
# 10 samples and 5 features
X = torch.randn(10, 5)

# Binary target labels
y = torch.randint(0, 2, (10, 1)).float()

In [18]:
# Training Pipeline
epochs = 100

for epoch in range(epochs):

    # Forward Pass
    predictions = model(X)

    # Calculate Loss
    loss = criterion(predictions, y)

    # Clear old gradients
    optimizer.zero_grad()

    # Backpropagation
    loss.backward()

    # Update weights
    optimizer.step()

    # Print loss
    if epoch % 10 == 0:
        print(f"Epoch: {epoch} Loss: {loss.item()}")

Epoch: 0 Loss: 0.2983366847038269
Epoch: 10 Loss: 0.29102784395217896
Epoch: 20 Loss: 0.2858918607234955
Epoch: 30 Loss: 0.28218719363212585
Epoch: 40 Loss: 0.27946919202804565
Epoch: 50 Loss: 0.2775881588459015
Epoch: 60 Loss: 0.2760385274887085
Epoch: 70 Loss: 0.27495989203453064
Epoch: 80 Loss: 0.27416789531707764
Epoch: 90 Loss: 0.2735121250152588
